// Generated by Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)
#ifndef BANUBAVIDEOEDITORSDK_SWIFT_H
#define BANUBAVIDEOEDITORSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreGraphics;
@import CoreMedia;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BanubaVideoEditorSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_PROTOCOL("_TtP20BanubaVideoEditorSDK21ActivityIndicatorView_")
@protocol ActivityIndicatorView
- (void)startAnimating;
- (void)stopAnimating;
@end

@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC20BanubaVideoEditorSDK19AlertViewController")
@interface AlertViewController : UIViewController
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end






SWIFT_PROTOCOL("_TtP20BanubaVideoEditorSDK14AnimatableView_")
@protocol AnimatableView
- (void)startWithCompletion:(void (^ _Nonnull)(BOOL))completion;
- (void)stop;
@end


SWIFT_PROTOCOL("_TtP20BanubaVideoEditorSDK21AnimatableViewFactory_")
@protocol AnimatableViewFactory
- (id <AnimatableView> _Nonnull)makeAnimatableView SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK12AudioService")
@interface AudioService : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AVAudioPlayer;

@interface AudioService (SWIFT_EXTENSION(BanubaVideoEditorSDK)) <AVAudioPlayerDelegate>
- (void)audioPlayerDidFinishPlaying:(AVAudioPlayer * _Nonnull)player successfully:(BOOL)flag;
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK11AudioWriter")
@interface AudioWriter : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AVAudioRecorder;

@interface AudioWriter (SWIFT_EXTENSION(BanubaVideoEditorSDK)) <AVAudioRecorderDelegate>
- (void)audioRecorderEncodeErrorDidOccur:(AVAudioRecorder * _Nonnull)recorder error:(NSError * _Nullable)error;
- (void)audioRecorderDidFinishRecording:(AVAudioRecorder * _Nonnull)recorder successfully:(BOOL)flag;
@end


@protocol BanubaVideoEditorSDKDelegate;
@class SDKService;
@class MusicEditorMetadata;
@class VideoEditorMetadata;
@class AVAsset;
@class MediaTrack;
@class AVAssetImageGenerator;
@class VideoEditorConfig;
@protocol ExternalViewControllerFactory;
@class UIImage;
@class ExportVideoConfiguration;

/// Video Editor main entity and entry point.
/// Can present and hide root view controller.
/// Has default export method.
SWIFT_CLASS("_TtC20BanubaVideoEditorSDK20BanubaVideoEditorSDK")
@interface BanubaVideoEditorSDK : NSObject
/// Video editor delegate
@property (nonatomic, weak) id <BanubaVideoEditorSDKDelegate> _Nullable delegate;
/// Service used to controll camera module.
/// Also provides access to video editor services.
@property (nonatomic, readonly, strong) SDKService * _Nonnull sdk;
/// Simple metadata of music composition settings
@property (nonatomic, readonly, strong) MusicEditorMetadata * _Nullable musicMetadata;
/// Simple metadata of video composition settings and overlay objects
@property (nonatomic, readonly, strong) VideoEditorMetadata * _Nullable metadata;
/// Currently edited AVAsset if any
@property (nonatomic, readonly, strong) AVAsset * _Nullable asset;
/// Music track which will be played on camera recording
@property (nonatomic, readonly, strong) MediaTrack * _Nullable musicTrack;
/// Asset image generator which may be used for video preview image creation
@property (nonatomic, readonly, strong) AVAssetImageGenerator * _Nullable imageGenerator;
/// Current video editor configuration
@property (nonatomic, readonly, strong) VideoEditorConfig * _Nonnull currentConfiguration;
/// BanubaVideoEditorSDK constructor
/// \param token token used to be able for access Banuba modules
///
/// \param effectsToken token used to be able for access Banuba effects
///
/// \param configuration contains all neccesory configurations for the editor
///
/// \param camera camera Module used to control device camera. Default is BanubaCameraModule
///
/// \param analytics used by editor to report analytics events
///
/// \param externalViewControllerFactory used by Banuba modules to use host view controllers
///
- (nonnull instancetype)initWithToken:(NSString * _Nonnull)token effectsToken:(NSString * _Nonnull)effectsToken configuration:(VideoEditorConfig * _Nonnull)configuration externalViewControllerFactory:(id <ExternalViewControllerFactory> _Nullable)externalViewControllerFactory OBJC_DESIGNATED_INITIALIZER;
/// Export video with default 1280x720 (or 1920x1080 on required devices) resolution
/// \param fileUrl url where exported video should be stored.
///
/// \param completion completion: (success, error), execute on background thread.
///
- (void)exportVideoWithFileUrl:(NSURL * _Nonnull)fileUrl completion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
/// Export video with default 1280x720 (or 1920x1080 on required devices) resolution and cover image
/// \param fileUrl url where exported video should be stored.
///
/// \param completion completion: (success, error, image), execute on background thread.
///
- (void)exportVideoWithCoverImageWithFileUrl:(NSURL * _Nonnull)fileUrl completion:(void (^ _Nonnull)(BOOL, NSError * _Nullable, UIImage * _Nonnull))completion;
/// Export several configurable video
/// \param configurations contains configurations for exporting videos such as file url,
/// watermark and video quality
///
/// \param completion completion: (success, error), execute on background thread.
///
- (void)exportVideosUsing:(NSArray<ExportVideoConfiguration *> * _Nonnull)configurations completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
/// Export several configurable video with cover image
/// \param configurations contains configurations for exporting videos such as file url,
/// watermark and video quality
///
/// \param completion completion: (success, error, image), execute on background thread.
///
- (void)exportVideosWithCoverImageUsing:(NSArray<ExportVideoConfiguration *> * _Nonnull)configurations completion:(void (^ _Nullable)(BOOL, NSError * _Nullable, UIImage * _Nonnull))completion;
/// Export audio from video
/// \param fileUrl url where exported video should be stored.
///
/// \param completion completion: (success, error), execute on background thread.
///
- (void)exportAudioWithFileUrl:(NSURL * _Nonnull)fileUrl completion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
/// Clear all session metadata
- (void)clearSessionData;
/// Dismiss Videoeditor’s root view controller
/// \param animated Pass true to animate the transition.
///
/// \param completion The block to execute after the view controller is dismissed.
///
- (void)dismissVideoEditorWithAnimated:(BOOL)animated completion:(void (^ _Nullable)(void))completion;
/// Modally presents Video editor’s root view controller
/// \param hostController The view controller to display over.
///
/// \param animated Pass true to animate the presentation.
///
/// \param musicTrack Music track which will be played on camera recording.
///
/// \param completion The block to execute after the presentation finishes.
///
- (void)presentVideoEditorFrom:(UIViewController * _Nonnull)hostController animated:(BOOL)animated musicTrack:(MediaTrack * _Nullable)musicTrack completion:(void (^ _Nullable)(void))completion;
/// Update video editor configuration
/// \param config The new version of configuration
///
- (void)updateVideoEditorConfig:(VideoEditorConfig * _Nonnull)config;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




/// Video Editor Delegate
SWIFT_PROTOCOL("_TtP20BanubaVideoEditorSDK28BanubaVideoEditorSDKDelegate_")
@protocol BanubaVideoEditorSDKDelegate
/// User canceled editing session
/// \param videoEditor video editor object informing the delegate about user action.
///
- (void)videoEditorDidCancel:(BanubaVideoEditorSDK * _Nonnull)videoEditor;
/// User finished editing session
/// \param videoEditor video editor object informing the delegate about user action.
///
- (void)videoEditorDone:(BanubaVideoEditorSDK * _Nonnull)videoEditor;
@end



SWIFT_CLASS("_TtC20BanubaVideoEditorSDK20ColorOnVideoMetadata")
@interface ColorOnVideoMetadata : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK11ColorParams")
@interface ColorParams : NSObject
- (nonnull instancetype)initWithRed:(float)red green:(float)green blue:(float)blue alpha:(float)alpha OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK17CoordinatesParams")
@interface CoordinatesParams : NSObject
@property (nonatomic, readonly) CGAffineTransform transform;
@property (nonatomic, readonly) CGRect frame;
- (nonnull instancetype)initWithTransform:(CGAffineTransform)transform frame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP20BanubaVideoEditorSDK28CountdownTimerAnimatableView_")
@protocol CountdownTimerAnimatableView <AnimatableView>
@property (nonatomic) NSInteger countdownDigit;
@end


SWIFT_PROTOCOL("_TtP20BanubaVideoEditorSDK25CountdownTimerViewFactory_")
@protocol CountdownTimerViewFactory
- (id <CountdownTimerAnimatableView> _Nonnull)makeCountdownTimerView SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK13CountdownView")
@interface CountdownView : UIView <CountdownTimerAnimatableView>
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)drawRect:(CGRect)rect;
@end


@interface CountdownView (SWIFT_EXTENSION(BanubaVideoEditorSDK))
@property (nonatomic) NSInteger countdownDigit;
- (void)startWithCompletion:(void (^ _Nonnull)(BOOL))completion;
- (void)stop;
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK25EditorEffectsConfigHolder")
@interface EditorEffectsConfigHolder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TimeMetadata;

SWIFT_CLASS("_TtC20BanubaVideoEditorSDK21EffectOnVideoMetadata")
@interface EffectOnVideoMetadata : NSObject
@property (nonatomic, readonly, strong) TimeMetadata * _Nonnull startTime;
@property (nonatomic, readonly, strong) TimeMetadata * _Nonnull endTime;
@property (nonatomic, readonly) NSUInteger effectId;
- (nonnull instancetype)initWithStartTime:(TimeMetadata * _Nonnull)startTime endTime:(TimeMetadata * _Nonnull)endTime effectId:(NSUInteger)effectId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP20BanubaVideoEditorSDK23EffectsProgressActivity_")
@protocol EffectsProgressActivity
@property (nonatomic) float progress;
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK24ExportVideoConfiguration")
@interface ExportVideoConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK21ExposureAnimationView")
@interface ExposureAnimationView : UIView <AnimatableView>
- (void)drawRect:(CGRect)rect;
- (void)startWithCompletion:(void (^ _Nonnull)(BOOL))completion;
- (void)stop;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol MusicEditorExternalViewControllerFactory;

SWIFT_PROTOCOL("_TtP20BanubaVideoEditorSDK29ExternalViewControllerFactory_")
@protocol ExternalViewControllerFactory
@property (nonatomic, strong) id <MusicEditorExternalViewControllerFactory> _Nullable musicEditorFactory;
@property (nonatomic, strong) id <CountdownTimerViewFactory> _Nullable countdownTimerViewFactory;
@property (nonatomic, strong) id <AnimatableViewFactory> _Nullable exposureViewFactory;
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK22FullscreenActivityView")
@interface FullscreenActivityView : UIView
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK18GIFOnVideoMetadata")
@interface GIFOnVideoMetadata : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSData * _Nullable imageData;
@property (nonatomic, readonly, strong) TimeMetadata * _Nonnull startTime;
@property (nonatomic, readonly, strong) TimeMetadata * _Nonnull endTime;
@property (nonatomic, readonly, strong) CoordinatesParams * _Nonnull coordinatesParams;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id imageData:(NSData * _Nullable)imageData startTime:(TimeMetadata * _Nonnull)startTime endTime:(TimeMetadata * _Nonnull)endTime coordinatesParams:(CoordinatesParams * _Nonnull)coordinatesParams OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK34GIFPickerDataLoadingViewController")
@interface GIFPickerDataLoadingViewController : UIViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK8GiphyAPI")
@interface GiphyAPI : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end





SWIFT_CLASS("_TtC20BanubaVideoEditorSDK16ImageCropperView")
@interface ImageCropperView : UIView
- (void)awakeFromNib;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC20BanubaVideoEditorSDK27InteractiveInterestMetadata")
@interface InteractiveInterestMetadata : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK23InteractivePollMetadata")
@interface InteractivePollMetadata : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK27InteractiveQuestionMetadata")
@interface InteractiveQuestionMetadata : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK28InteractiveTestFieldMetaData")
@interface InteractiveTestFieldMetaData : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK23InteractiveTestMetadata")
@interface InteractiveTestMetadata : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class MusicEditorTrack;

SWIFT_CLASS("_TtC20BanubaVideoEditorSDK19MusicEditorMetadata")
@interface MusicEditorMetadata : NSObject
@property (nonatomic, copy) NSArray<MusicEditorTrack *> * _Nonnull tracks;
- (nonnull instancetype)initWithTracks:(NSArray<MusicEditorTrack *> * _Nonnull)tracks OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK16MusicEditorTrack")
@interface MusicEditorTrack : NSObject
@property (nonatomic, copy) NSURL * _Nonnull url;
@property (nonatomic, copy) NSURL * _Nonnull originalURL;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic) int64_t id;
- (nonnull instancetype)initWithPosition:(NSInteger)position timeScale:(NSTimeInterval)timeScale compositionStart:(NSTimeInterval)compositionStart timeRangeStart:(NSTimeInterval)timeRangeStart timeRangeEnd:(NSTimeInterval)timeRangeEnd url:(NSURL * _Nonnull)url originalURL:(NSURL * _Nonnull)originalURL isAudioRecord:(BOOL)isAudioRecord applyedFilterId:(NSInteger)applyedFilterId title:(NSString * _Nonnull)title id:(int64_t)id OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




SWIFT_CLASS("_TtC20BanubaVideoEditorSDK37PhotoVideoCaptureButtonViewController")
@interface PhotoVideoCaptureButtonViewController : UIViewController
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end





SWIFT_CLASS("_TtC20BanubaVideoEditorSDK32PreviewSingleVideoViewController")
@interface PreviewSingleVideoViewController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end



SWIFT_CLASS("_TtC20BanubaVideoEditorSDK16PreviewVideoView")
@interface PreviewVideoView : UIImageView
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK10SDKService")
@interface SDKService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC20BanubaVideoEditorSDK17SpeedSelectionBar")
@interface SpeedSelectionBar : UIView
- (void)awakeFromNib;
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@class TextParams;

SWIFT_CLASS("_TtC20BanubaVideoEditorSDK19TextOnVideoMetadata")
@interface TextOnVideoMetadata : NSObject
@property (nonatomic, readonly, copy) NSData * _Nullable imageData;
@property (nonatomic, readonly, strong) TextParams * _Nonnull textParams;
@property (nonatomic, readonly, strong) TimeMetadata * _Nonnull startTime;
@property (nonatomic, readonly, strong) TimeMetadata * _Nonnull endTime;
@property (nonatomic, readonly, strong) CoordinatesParams * _Nonnull coordinatesParams;
- (nonnull instancetype)initWithImageData:(NSData * _Nullable)imageData textParams:(TextParams * _Nonnull)textParams startTime:(TimeMetadata * _Nonnull)startTime endTime:(TimeMetadata * _Nonnull)endTime coordinatesParams:(CoordinatesParams * _Nonnull)coordinatesParams OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK10TextParams")
@interface TextParams : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK12TimeMetadata")
@interface TimeMetadata : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface TimeMetadata (SWIFT_EXTENSION(BanubaVideoEditorSDK))
- (nonnull instancetype)initWithCmTime:(CMTime)cmTime;
- (CMTime)getCMTime SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK22TimelineViewController")
@interface TimelineViewController : UIViewController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end



















SWIFT_CLASS("_TtC20BanubaVideoEditorSDK28VideoEditorActivityIndicator")
@interface VideoEditorActivityIndicator : UIView
@property (nonatomic) CGRect bounds;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK17VideoEditorConfig")
@interface VideoEditorConfig : NSObject
- (nonnull instancetype)init;
@end

@class VideoInteractiveMetadata;
@class VideoMetadata;

SWIFT_CLASS("_TtC20BanubaVideoEditorSDK19VideoEditorMetadata")
@interface VideoEditorMetadata : NSObject
@property (nonatomic, readonly, copy) NSArray<EffectOnVideoMetadata *> * _Nullable effectsOnVideoMetadata;
@property (nonatomic, readonly, strong) ColorOnVideoMetadata * _Nullable colorOnVideoMetadata;
@property (nonatomic, readonly, copy) NSArray<TextOnVideoMetadata *> * _Nullable textOnVideoMetadata;
@property (nonatomic, readonly, copy) NSArray<GIFOnVideoMetadata *> * _Nullable gifOnVideoMetadata;
@property (nonatomic, readonly, strong) VideoInteractiveMetadata * _Nonnull videoInteractiveMetadata;
@property (nonatomic, strong) VideoMetadata * _Nullable videoMetadata;
- (nonnull instancetype)initWithEffectsOnVideoMetadata:(NSArray<EffectOnVideoMetadata *> * _Nullable)effectsOnVideoMetadata colorOnVideoMetadata:(ColorOnVideoMetadata * _Nullable)colorOnVideoMetadata textOnVideoMetadata:(NSArray<TextOnVideoMetadata *> * _Nullable)textOnVideoMetadata gifOnVideoMetadata:(NSArray<GIFOnVideoMetadata *> * _Nullable)gifOnVideoMetadata videoInteractiveMetadata:(VideoInteractiveMetadata * _Nonnull)videoInteractiveMetadata videoMetadata:(VideoMetadata * _Nullable)videoMetadata OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK23VideoEditorTrimMetadata")
@interface VideoEditorTrimMetadata : NSObject
@property (nonatomic, copy) NSURL * _Nonnull url;
@property (nonatomic, copy) NSData * _Nullable imageData;
- (nonnull instancetype)initWithUrl:(NSURL * _Nonnull)url imageData:(NSData * _Nullable)imageData OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK24VideoInteractiveMetadata")
@interface VideoInteractiveMetadata : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20BanubaVideoEditorSDK13VideoMetadata")
@interface VideoMetadata : NSObject
@property (nonatomic, readonly) BOOL isSlideShow;
- (nonnull instancetype)initWithIsSlideShow:(BOOL)isSlideShow OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
